### ISSUE TITLE
JSON Format in Block Takes out Server

### ISSUE THREAD

**Issue by arpee** [SaitoTech/saito-lite-rust#329]
prod.saito.io fell over with the following error:

```
19|npm run dev  | cleanupDisconnectedPeer : peer count = 35
19|npm run dev  | cleanupDisconnectedPeer : peer count = 35
19|npm run dev  | cleanupDisconnectedPeer : peer count = 35
19|npm run dev  | cleanupDisconnectedPeer : peer count = 35
19|npm run dev  | cleanupDisconnectedPeer : peer count = 35
19|npm run dev  | cleanupDisconnectedPeer : peer count = 35
19|npm run dev  | RECEIVED REQGSTCN with fork_id: c13b0000000000000000000000000000 and block_id 44344
19|npm run dev  | last shared ancestor generated at: 44340
19|npm run dev  | mining loop...
19|npm run dev  | SyntaxError: Unexpected token @ in JSON at position 0
19|npm run dev  |     at JSON.parse (<anonymous>)
19|npm run dev  |     at createStrictSyntaxError (/opt/saito/node_modules/body-parser/lib/types/json.js:158:10)
19|npm run dev  |     at parse (/opt/saito/node_modules/body-parser/lib/types/json.js:83:15)
19|npm run dev  |     at /opt/saito/node_modules/body-parser/lib/read.js:121:18
19|npm run dev  |     at invokeCallback (/opt/saito/node_modules/raw-body/index.js:224:16)
19|npm run dev  |     at done (/opt/saito/node_modules/raw-body/index.js:213:7)
19|npm run dev  |     at IncomingMessage.onEnd (/opt/saito/node_modules/raw-body/index.js:273:7)
19|npm run dev  |     at IncomingMessage.emit (node:events:532:35)
19|npm run dev  |     at endReadableNT (node:internal/streams/readable:1346:12)
19|npm run dev  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
19|npm run dev  | SyntaxError: Unexpected token @ in JSON at position 0
19|npm run dev  |     at JSON.parse (<anonymous>)
19|npm run dev  |     at createStrictSyntaxError (/opt/saito/node_modules/body-parser/lib/types/json.js:158:10)
19|npm run dev  |     at parse (/opt/saito/node_modules/body-parser/lib/types/json.js:83:15)
19|npm run dev  |     at /opt/saito/node_modules/body-parser/lib/read.js:121:18
19|npm run dev  |     at invokeCallback (/opt/saito/node_modules/raw-body/index.js:224:16)
19|npm run dev  |     at done (/opt/saito/node_modules/raw-body/index.js:213:7)
19|npm run dev  |     at IncomingMessage.onEnd (/opt/saito/node_modules/raw-body/index.js:273:7)
19|npm run dev  |     at IncomingMessage.emit (node:events:532:35)
19|npm run dev  |     at endReadableNT (node:internal/streams/readable:1346:12)
19|npm run dev  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
19|npm run dev  | mining loop...
19|npm run dev  | mining loop...
19|npm run dev  | Total Work Needed: 0 ---- available ---> 0     (0 / 1)
19|npm run dev  | blockring reports PBH: 38d1c40b6884149460aeed9ccf89e1de16d07c5bb5c0de0c8451188013fef30c
19|npm run dev  | -----------------------------------
19|npm run dev  | how many gts to check? 0
19|npm run dev  | -----------------------------------
19|npm run dev  | Mempool : adding block... : 06e16ed108a73a4810257cd8e2575284ac26c7352b41d0dc8fb7696220408e4f
19|npm run dev  | blockchain.addBlockToBlockchain : 06e16ed108a73a4810257cd8e2575284ac26c7352b41d0dc8fb7696220408e4f
19|npm run dev  | approving 06e16ed108a73a4810257cd8e2575284ac26c7352b41d0dc8fb7696220408e4f as genesis block
19|npm run dev  | blockchain.downgradeBlockchainData
19|npm run dev  | block af7549c5e468022bef0426af31bd9636254e60f9166c015f4ea621cd3890f480 type set as pruned
19|npm run dev  | network.propagateBlock 06e16ed108a73a4810257cd8e2575284ac26c7352b41d0dc8fb7696220408e4f
19|npm run dev  | mining loop...
19|npm run dev  | Error: write after end
19|npm run dev  |     at new NodeError (node:internal/errors:371:5)
19|npm run dev  |     at write_ (node:_http_outgoing:748:11)
19|npm run dev  |     at ServerResponse.write (node:_http_outgoing:707:15)
19|npm run dev  |     at ReadStream.ondata (node:internal/streams/readable:754:22)
19|npm run dev  |     at ReadStream.emit (node:events:520:28)
19|npm run dev  |     at addChunk (node:internal/streams/readable:315:12)
19|npm run dev  |     at readableAddChunk (node:internal/streams/readable:289:9)
19|npm run dev  |     at ReadStream.Readable.push (node:internal/streams/readable:228:10)
19|npm run dev  |     at node:internal/fs/streams:275:14
19|npm run dev  |     at FSReqCallback.wrapper [as oncomplete] (node:fs:660:5)
19|npm run dev  | fetching block : 06e16ed108a73a4810257cd8e2575284ac26c7352b41d0dc8fb7696220408e4f
19|npm run dev  | [ERROR] 01:25:31 Error: write after end
19|npm run dev  | Shutting down Saito
19|npm run dev  | Network Shutdown
```

On restart it appeared to resolve a form and has continued without issue for 30 minutes.

**Comment by trevelyan** [comment]
This issue should be fixed.
